apiVersion: test/v1
kind: hotpatch
describtion: "hongchunhua hotpatch"
metadata:
  name: "hot patch"
spec:
  - name: mytest
    path: /root/develop/photpatch/build/lib/libpatch.so
    pre_patch_callback: false
    post_patch_callback: false
    pre_unpatch_callback: false
    post_unpatch_callback: false
    function:
    - newname: helloworld
      oldname: helloworld
      newaddr: 
      oldaddr: none


